#!/usr/bin/python3
import sys
print(sys.path)
from math import gcd 
import random
from sympy import isprime

def generate_public(phi_n):
    # we want to choose an e that is relatively prime to pq
    # p and q are both primes. the only numbers that are not relatively prime to pq are p and q. so we can choose an e such that e is 
    # somewhere in the range from 1 - pq such that e is not p or q. 
    relative_prime = False
    
    while not relative_prime:
        #print("entering relative prime for e test")
        e = random.randint(2, phi_n) # randomly choose a number in between 2 and phi of n (we don't want to choose 1, that doesn't encrypt)
        if gcd(e, phi_n) == 1:
            relative_prime = True # we've found a possible e—continue
    #print("this is e: ", e)
    #print("exited e")
    return e
    
def euclid_extended(e, phi):
    """ Use this to find the multiplicative inverse for a given phi of n and key e. Euclid's Extended Division Algorithm attempts to find
    the values x and y such that ax + by = gcd(a, b). In this case, we care about the coefficient for a. This will tell us the multiplicative inverse.
    I referenced this video to create this code: 
    https://www.youtube.com/watch?v=kYasb426Yjk. 
    """
    # first run the euclidean algorithm, then keep track of old variables for backtracking
    d = 0
    x1 = 0
    x2 = 1
    y1 = 1
    z = phi

    while e > 0:
        intdiv = z//e
        
        remainder = z - intdiv * e

        z = e 

        e = remainder
      
        # store old variables by substituting in old vals
        x = x2 - (intdiv * x1)
       
        y = d - (intdiv * y1)
      
        # preserve previous values and implement the "backtracking" in euclid's extended algorithm
        d = y1
        y1 = y
        x2 = x1
        x1 = x
  
    
    if d < 0: # neg case. we need multiplicative inverse to be positive
        return d + phi
    else: # normal positive case
        return d
    
    
def phi(p):
    # this uses the number theory principle and requires both p and q to be prime. This is *sort of* cheating. there's a much slower way 
    # to calculate this using the gcd function from the math library. This just assumes that the input is prime
    return p-1
def encrypt(plaintext, key, mod):
    cipher = [pow(ord(char), key, mod) for char in plaintext]
    cipher = []
    cipher_letter = []
    for letter in plaintext:
        cipher.append(pow(ord(letter), key, mod))
    print("this is the key: ", key)
    print("this is the mod: ", mod)
    for val in cipher:
        print("this is val: ", val)
        print("this is the key: ", key)
        print("this is the mod: ", mod)
        cipher_letter.append(chr(int(val)))
    print("this is the encrypted message: ", ''.join(cipher_letter))
    return cipher # this returns is as an array of bytes in unicode format
def retrieve_private_key(phi, key):
    # using p and q: want to find some d > 0 such that de = 1 mod phi n 
    # so we want to use euclid's extended division algorithm
    # and then check if the result is negative. if it is negative, then add to n to get pos version d
    return euclid_extended(key, phi)
    
    
def decrypt(cipher, key, mod):
    # note that mod is pq 
    #decrypt_vals = []
    #text = []
    #for letter in cipher:
        #decrypt_vals.append(str(pow(letter, key, mod)))
    plain = [str(pow(char, key, mod)) for char in cipher]
    #print("this is just ints in decrypt: ", decrypt_vals)
    text = [chr(int(char)) for char in plain]
    #for val in decrypt_vals:
        #text.append(chr(int(val)))
    #print('this is plaintext after cipher: ', text)
    return text
def rsa(p, q, plaintext):
    #primality_test(p, q) implement this later!
    n = p*q
    print('this is n: ', n)
    phi_n = phi(p) * phi(q)
    public_key = generate_public(phi_n)
    print("this is the public key: ", public_key)
    cipher = encrypt(plaintext, public_key, n)
    print('cipher: ' , cipher)
    print("this is phi of n: ", phi_n)
    
    private_key = retrieve_private_key(phi_n, public_key)
    print("this is the private_key: ", private_key)
    plain = decrypt(cipher, private_key, n)
    print("This is your original message: ", ''.join(plain))
    

#TODO: 
# 1. Implement basic RSA using user input for primes (foundation implementation) 
# 2. set this up with PBT/have PBT generate primes. first assume that all inputs are prime numbers. 
#    (oracle should at this point just be checking that the decrypted message is the same as the plaintext that's been passed in)
# 3. find way for RSA to "check" for primes (using the miller-rabin test maybe)
# 4. Update Oracle to also generate non-prime numbers to input into RSA. we want RSA to reject non-prime numbers in *most* cases
# 5. Then update RSA to include digital signatures
# 6. Alloy model (ask Alexa about what kind of Alloy model this should be)

def main():
    # read input from std in
    # we expect input to have this order: p1 p2 plaintext (with one space in between them) when run from command line
    if len(sys.argv) != 4:
        print("Please use format: ./rsa prime1 prime2 'plaintext goes here' separated by spaces.")
    else:
        # first check that inputs are correct
        p1 = int(sys.argv[1])
        p2 = int(sys.argv[2])
        plaintext = sys.argv[3]
        if (not isprime(p1) or not isprime(p2)): # case where inputs are not prime
            raise ValueError("Please input only prime numbers!")
        else:
            return rsa(p1, p2, plaintext)
if __name__ == "__main__":
    main()